# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import backend_pb2 as backend__pb2


class WsProtoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addPostEvent = channel.unary_unary(
                '/WsProto/addPostEvent',
                request_serializer=backend__pb2.NewPost.SerializeToString,
                response_deserializer=backend__pb2.Users.FromString,
                )
        self.deletePostEvent = channel.unary_unary(
                '/WsProto/deletePostEvent',
                request_serializer=backend__pb2.Post.SerializeToString,
                response_deserializer=backend__pb2.NULL.FromString,
                )
        self.changePostEvent = channel.unary_unary(
                '/WsProto/changePostEvent',
                request_serializer=backend__pb2.Post.SerializeToString,
                response_deserializer=backend__pb2.NULL.FromString,
                )
        self.changePostLikeEvent = channel.unary_unary(
                '/WsProto/changePostLikeEvent',
                request_serializer=backend__pb2.PostLike.SerializeToString,
                response_deserializer=backend__pb2.NULL.FromString,
                )


class WsProtoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addPostEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deletePostEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def changePostEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def changePostLikeEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WsProtoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addPostEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.addPostEvent,
                    request_deserializer=backend__pb2.NewPost.FromString,
                    response_serializer=backend__pb2.Users.SerializeToString,
            ),
            'deletePostEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.deletePostEvent,
                    request_deserializer=backend__pb2.Post.FromString,
                    response_serializer=backend__pb2.NULL.SerializeToString,
            ),
            'changePostEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.changePostEvent,
                    request_deserializer=backend__pb2.Post.FromString,
                    response_serializer=backend__pb2.NULL.SerializeToString,
            ),
            'changePostLikeEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.changePostLikeEvent,
                    request_deserializer=backend__pb2.PostLike.FromString,
                    response_serializer=backend__pb2.NULL.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WsProto', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WsProto(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addPostEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WsProto/addPostEvent',
            backend__pb2.NewPost.SerializeToString,
            backend__pb2.Users.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deletePostEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WsProto/deletePostEvent',
            backend__pb2.Post.SerializeToString,
            backend__pb2.NULL.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def changePostEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WsProto/changePostEvent',
            backend__pb2.Post.SerializeToString,
            backend__pb2.NULL.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def changePostLikeEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WsProto/changePostLikeEvent',
            backend__pb2.PostLike.SerializeToString,
            backend__pb2.NULL.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
