# Generated by Django 4.2 on 2023-05-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='repost_id',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
