# Generated by Django 4.2 on 2023-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_posts_likes_count_alter_posts_repost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='repost_id',
            field=models.IntegerField(default=-1),
        ),
    ]
